version: '3.8'

services:
  adminer:
    image: adminer
    container_name: adminer-admin
    networks:
      - test_network
    restart: always
    ports:
      - '1400:8080'
  user-storage:
    container_name: user-storage
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - test_network
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - user-volumes:/var/lib/mysql
      - ./user-db/mysql.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  test_network:
    driver: bridge

volumes:
  user-volumes:
    driver: local