config:
  cloud-server:
    url: ${CLOUD_SERVER_URL:localhost}
    port: ${CLOUD_SERVER_PORT:7000}
    active-profile: ${ACTIVE_PROFILE:dev}
  eureka-server:
    url: ${EUREKA_SERVER_URL:localhost}
    port: ${EUREKA_SERVER_PORT:7100}
  zipkin-server:
    url: ${ZIPKIN_SERVER_URL:localhost}
    port: ${ZIPKIN_SERVER_PORT:9411}
  server:
    port: ${SERVER_PORT:7200}

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://${config.cloud-server.url}:${config.cloud-server.port}
  profiles:
    active: ${config.cloud-server.active-profile}
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://${config.zipkin-server.url}:${config.zipkin-server.port}/

server:
  port: ${config.server.port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${config.eureka-server.url}:${config.eureka-server.port}/eureka