config:
  cloud-server:
    url: ${CLOUD_SERVER_URL:localhost}
    port: ${CLOUD_SERVER_PORT:7000}
    active-profile: ${ACTIVE_PROFILE:dev}
  eureka-server:
    url: ${EUREKA_SERVER_URL:localhost}
    port: ${EUREKA_SERVER_PORT:7100}
  server:
    port: ${SERVER_PORT:7100}

spring:
  application:
    name: naming-server
  config:
    import: optional:configserver:http://${config.cloud-server.url}:${config.cloud-server.port}
  profiles:
    active: ${config.cloud-server.active-profile}

server:
  port: ${config.server.port}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${config.eureka-server.url}:${config.eureka-server.port}/eureka