config:
  cloud-server: ${CLOUD_SERVER_URL:http://localhost:8000}
  active-profile: ${ACTIVE_PROFILE:dev}
  server:
    port: ${SERVER_PORT:8080}

spring:
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 3000
        multiplier: 1.2
        max-interval: 10000
        max-attempts: 6

  application:
    name: jwt-service
  config:
    import: optional:configserver:${config.cloud-server}
  profiles:
    active: ${config.active-profile}

server:
  port: ${config.server.port}