config:
  cloud-server:
    url: ${CLOUD_SERVER_URL:localhost}
    port: ${CLOUD_SERVER_PORT:7000}
    active-profile: ${ACTIVE_PROFILE:dev}
  eureka-server:
    url: ${EUREKA_SERVER_URL:localhost}
    port: ${EUREKA_SERVER_PORT:7100}
  zipkin-server:
    url: ${ZIPKIN_SERVER_URL:localhost}
    port: ${ZIPKIN_SERVER_PORT:9411}
  server:
    port: ${SERVER_PORT:8000}
  database:
    port: ${DATABASE_PORT:3306}
    address: ${DATABASE_URL:localhost}
    name: ${DATABASE_NAME:user_db}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root@123}


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: jwt-service
  config:
    import: optional:configserver:http://${config.cloud-server.url}:${config.cloud-server.port}
  profiles:
    active: ${config.cloud-server.active-profile}
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://${config.zipkin-server.url}:${config.zipkin-server.port}/
  datasource:
    url: jdbc:mysql://${config.database.address}:${config.database.port}/${config.database.name}
    username: ${config.database.username}
    password: ${config.database.password}
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
server:
  port: ${config.server.port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${config.eureka-server.url}:${config.eureka-server.port}/eureka


jwt:
  header: "Authorization"
  prefix: "Bearer "
  secret: "jwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecret"
  duration: 180000
  issuer: "JWT Microservice"